http:
  # bind ip address
  address: localhost
  # bind ip port
  port: 8080

file:
  # pattern for affiliated files => /home/pavels/Log/APP1.log
  file_template: '/home/pavels/Log/{{affiliation}}.log'

rules:
  # field rule is only one - field specifies LogRecord's property
  # logger, level, message, time
  - { field: app, is_equal: APP1, targets: console }
  # regular expression rule(s)
  # match target by regular expression
  - { re: \d+, targets: file }

console:
  colors:
    Debug: grey
    Error: red
    Info: green
