http:
  # bind ip address
  address: localhost
  # bind ip port
  port: 8080

rules:
  # field specifies LogRecord's property
  # logger, level, message, time
  - { field: app, is_equal: APP1, target: null }
  - { field: app, is_equal: APP2, target: /home/pavels/Log/APP2.log }
  # regular expression rule(s)
  # match target by regular expression
  - { re: \d+, target: /home/pavels/Log/APP1.log }

console:
  colors:
    Debug: grey
    Error: red
    Info: green
